server:
  port: 996
  servlet:
    context-path:
spring:
  profiles:
    active:
  application:
    name: erueka-server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
