server:
  port: 999
  servlet:
    context-path:
spring:
  profiles:
    active: dev
  application:
    name: feign
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.example.SimpleErrorDecoder
        retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.example.FooRequestInterceptor
          - com.example.BarRequestInterceptor
        decode404: false
        encoder: default
        decoder: com.example.SimpleDecoder
        contract: com.example.SimpleContract

